#!/usr/bin/env python

# script to plot rmsd values generated by cpptraj with title

import matplotlib.pyplot as plt
import os

cwd = os.getcwd()
mutation = cwd.split("/")[-1]
super = cwd.split("/")[-2]
title = (super + " " + mutation + ": Production 1-4 \n Distance values of hairpin with light and heavy chain")

values = []

with open("distance_prod_long_hairpin.dat",'r') as f:
    f.readline()
    for line in f:
        values.append(float(line.split("    ")[2][3:-1]))

plt.plot(values)
plt.ylim([6,9])
plt.title(title)
plt.savefig("distance_prod_long_hairpin.png")