#!/usr/bin/env python

import sys
import argparse
import numpy as np
from scipy.stats.stats import pearsonr

def main(argv):
    parser = argparse.ArgumentParser(description='Plot residue interactions.')
    parser.add_argument('infile', help='csv generated by consolidate_distance_cpptraj_each')
    parser.add_argument('energy', help='energy values')
    parser.add_argument('outfile', help='outfile')
    args = parser.parse_args()

    energies = []
    with open(args.energy, 'r') as f:
        f.readline()
        for line in f:
            energies.append(float(line))

    table = []
    header = []
    with open(args.infile, 'r') as f:
        # remove '/n' at end of line
        for line in f:
            line = line.split(',')
            header.append(line[0])
            table.append(line[1:])
            # line = line.split(',')
            # table.append(line)
    table = [[float(y) for y in x] for x in table]

    # calculate pearson correlation for every distance
    correlations = []
    for column in table:
        correlations.append(pearsonr(energies,column))

    with open(args.outfile, 'w') as f:
        if len(correlations) != len(header):
            print "correlations and header differ in length"
            return
        for i in range(0,len(correlations)):
            f.write(header[i] + ", " + str(correlations[i][0]) + ", " + str(correlations[i][1]) + "\n")

if __name__ == "__main__":
    main(sys.argv)