#!/usr/bin/env python

# script to plot rmsd values generated by cpptraj with title

import matplotlib.pyplot as plt
import os

cwd = os.getcwd()
mutation = cwd.split("/")[-1]
super = cwd.split("/")[-2]
title = (super + " " + mutation + ": Production 1-4 \n RMSD values of hairpin region (2186-2210)")

values = []

with open("rmsd_prod_long_hairpin.dat",'r') as f:
    f.readline()
    for line in f:
        values.append(float(line.split("    ")[2][3:-1]))

plt.plot(values)
plt.title(title)
plt.show()